# Generated by Django 3.2.4 on 2021-09-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.TextField()),
                ("title", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=100)),
            ],
        ),
    ]
